version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: webpack
    versions:
    - 5.18.0
    - 5.19.0
    - 5.20.0
    - 5.20.1
    - 5.20.2
    - 5.21.2
    - 5.22.0
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.8.0
    - 13.0.0
    - 13.0.1
    - 13.0.2
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.1.2
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.8
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.13.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.14
