version: '3.7'

# The x- prefix lets docker compose ignore the key
x-define-images-and-volumes: &define_images_and_volumes
  depends_on:
    - base_image_builder
  image: production-publisher-base

services:
  base_image_builder:
    # Name the image we build here so we can reuse it
    image: production-publisher-base
    build:
      context: ../../../
      dockerfile: ./config/docker/production/Dockerfile

  server:
    <<: *define_images_and_volumes
    ports:
      - 8080:8080
    environment:
      PORT: 8080
    command: node dist/server.js
